### ISSUE TITLE
recycling this deprecated name on npm?

### ISSUE THREAD

**Issue by WebReflection** [medikoo/node-ext#2]
I wanted to contact you via PVT on twitter but for some reason you don't follow me so here I am.

You flagged this as deprecated, mind passing this name to me so I can bump a new major and push a completely different library borrowing `next` name?

The TL;DR version of that library is `next.frame(cb)` or `next.idle(cb)` or `next.clear(cb)` to optimize, and centralize, `requestAnimationFrame` and `requestIdleCallback` operations in a smarter way, similar to `process.nextTick` in node, but compeltely browser-side centric.

Please let me know if that works for you, otherwise I'll try to find another name
( but unfortunately cool names are all taken on npm :-( )

Cheers

**Comment by medikoo** [comment]
@WebReflection A while ago I've already passed this module to @rauchg.

@rauchg do you need this (I don't see anything published)? If not, then I think we should be happy to pass it to @WebReflection (assuming I'll maintain the rights to publish updates to v0.4 version).
Let us know

**Comment by WebReflection** [comment]
ping for @rauchg ... by any chance you can hand over the repo to me?
This is me on npm, thank you https://www.npmjs.com/~webreflection

**Comment by medikoo** [comment]
@WebReflection I took that to email (it'll probably work better), therfore closing this issue
